/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AchievementManager {
  export type AchievementStruct = {
    name: string;
    description: string;
    flagIndex: BigNumberish;
    badgeTokenId: BigNumberish;
    criteriaType: BigNumberish;
    criteriaValue: BigNumberish;
  };

  export type AchievementStructOutput = [
    name: string,
    description: string,
    flagIndex: bigint,
    badgeTokenId: bigint,
    criteriaType: bigint,
    criteriaValue: bigint
  ] & {
    name: string;
    description: string;
    flagIndex: bigint;
    badgeTokenId: bigint;
    criteriaType: bigint;
    criteriaValue: bigint;
  };
}

export interface AchievementManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "achievements"
      | "addAchievement"
      | "badgeNFT"
      | "checkAchievements"
      | "gamesPlayed"
      | "getAllAchievements"
      | "getPlayerAchievements"
      | "mintAchievementBadge"
      | "owner"
      | "perfectGames"
      | "playerProfile"
      | "quizContract"
      | "renounceOwnership"
      | "setQuizContract"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AchievementAdded"
      | "AchievementUnlocked"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "achievements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addAchievement",
    values: [
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "badgeNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "checkAchievements",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gamesPlayed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAchievements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerAchievements",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintAchievementBadge",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "perfectGames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "playerProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quizContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setQuizContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "achievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "badgeNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkAchievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "gamesPlayed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAchievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerAchievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintAchievementBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "perfectGames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quizContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuizContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AchievementAddedEvent {
  export type InputTuple = [flagIndex: BigNumberish, name: string];
  export type OutputTuple = [flagIndex: bigint, name: string];
  export interface OutputObject {
    flagIndex: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AchievementUnlockedEvent {
  export type InputTuple = [
    player: AddressLike,
    flagIndex: BigNumberish,
    name: string
  ];
  export type OutputTuple = [player: string, flagIndex: bigint, name: string];
  export interface OutputObject {
    player: string;
    flagIndex: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AchievementManager extends BaseContract {
  connect(runner?: ContractRunner | null): AchievementManager;
  waitForDeployment(): Promise<this>;

  interface: AchievementManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  achievements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        name: string;
        description: string;
        flagIndex: bigint;
        badgeTokenId: bigint;
        criteriaType: bigint;
        criteriaValue: bigint;
      }
    ],
    "view"
  >;

  addAchievement: TypedContractMethod<
    [
      name: string,
      desc: string,
      flagIndex: BigNumberish,
      tokenId: BigNumberish,
      cType: BigNumberish,
      cValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  badgeNFT: TypedContractMethod<[], [string], "view">;

  checkAchievements: TypedContractMethod<
    [player: AddressLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;

  gamesPlayed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getAllAchievements: TypedContractMethod<
    [],
    [AchievementManager.AchievementStructOutput[]],
    "view"
  >;

  getPlayerAchievements: TypedContractMethod<
    [player: AddressLike],
    [[boolean[], boolean[]] & { unlocked: boolean[]; minted_: boolean[] }],
    "view"
  >;

  mintAchievementBadge: TypedContractMethod<
    [achievementIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  perfectGames: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  playerProfile: TypedContractMethod<[], [string], "view">;

  quizContract: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setQuizContract: TypedContractMethod<
    [_quiz: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "achievements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint] & {
        name: string;
        description: string;
        flagIndex: bigint;
        badgeTokenId: bigint;
        criteriaType: bigint;
        criteriaValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "addAchievement"
  ): TypedContractMethod<
    [
      name: string,
      desc: string,
      flagIndex: BigNumberish,
      tokenId: BigNumberish,
      cType: BigNumberish,
      cValue: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "badgeNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkAchievements"
  ): TypedContractMethod<
    [player: AddressLike, score: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "gamesPlayed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAllAchievements"
  ): TypedContractMethod<
    [],
    [AchievementManager.AchievementStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerAchievements"
  ): TypedContractMethod<
    [player: AddressLike],
    [[boolean[], boolean[]] & { unlocked: boolean[]; minted_: boolean[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintAchievementBadge"
  ): TypedContractMethod<
    [achievementIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "perfectGames"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "playerProfile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quizContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuizContract"
  ): TypedContractMethod<[_quiz: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AchievementAdded"
  ): TypedContractEvent<
    AchievementAddedEvent.InputTuple,
    AchievementAddedEvent.OutputTuple,
    AchievementAddedEvent.OutputObject
  >;
  getEvent(
    key: "AchievementUnlocked"
  ): TypedContractEvent<
    AchievementUnlockedEvent.InputTuple,
    AchievementUnlockedEvent.OutputTuple,
    AchievementUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AchievementAdded(uint8,string)": TypedContractEvent<
      AchievementAddedEvent.InputTuple,
      AchievementAddedEvent.OutputTuple,
      AchievementAddedEvent.OutputObject
    >;
    AchievementAdded: TypedContractEvent<
      AchievementAddedEvent.InputTuple,
      AchievementAddedEvent.OutputTuple,
      AchievementAddedEvent.OutputObject
    >;

    "AchievementUnlocked(address,uint8,string)": TypedContractEvent<
      AchievementUnlockedEvent.InputTuple,
      AchievementUnlockedEvent.OutputTuple,
      AchievementUnlockedEvent.OutputObject
    >;
    AchievementUnlocked: TypedContractEvent<
      AchievementUnlockedEvent.InputTuple,
      AchievementUnlockedEvent.OutputTuple,
      AchievementUnlockedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
