/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DailyQuizInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "QUESTIONS_PER_DAY"
      | "achievementManager"
      | "canPlay"
      | "dailyMerkleRoot"
      | "dailyScore"
      | "enterQuiz"
      | "getTodayScore"
      | "hasSubmitted"
      | "isTodayReady"
      | "lastPlayedDay"
      | "owner"
      | "playerProfile"
      | "renounceOwnership"
      | "setDailyMerkleRoot"
      | "submitAnswers"
      | "todayIndex"
      | "totalGamesPlayed"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MerkleRootSet"
      | "OwnershipTransferred"
      | "QuizCompleted"
      | "QuizEntered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "QUESTIONS_PER_DAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "achievementManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canPlay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyMerkleRoot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "enterQuiz", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTodayScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTodayReady",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastPlayedDay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playerProfile",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyMerkleRoot",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAnswers",
    values: [BytesLike[], BytesLike[][]]
  ): string;
  encodeFunctionData(
    functionFragment: "todayIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalGamesPlayed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "QUESTIONS_PER_DAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "achievementManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canPlay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dailyMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dailyScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "enterQuiz", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTodayScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTodayReady",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastPlayedDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playerProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAnswers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "todayIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalGamesPlayed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MerkleRootSetEvent {
  export type InputTuple = [dayIndex: BigNumberish, root: BytesLike];
  export type OutputTuple = [dayIndex: bigint, root: string];
  export interface OutputObject {
    dayIndex: bigint;
    root: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuizCompletedEvent {
  export type InputTuple = [
    player: AddressLike,
    dayIndex: BigNumberish,
    score: BigNumberish,
    boostedScore: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    dayIndex: bigint,
    score: bigint,
    boostedScore: bigint
  ];
  export interface OutputObject {
    player: string;
    dayIndex: bigint;
    score: bigint;
    boostedScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuizEnteredEvent {
  export type InputTuple = [player: AddressLike, dayIndex: BigNumberish];
  export type OutputTuple = [player: string, dayIndex: bigint];
  export interface OutputObject {
    player: string;
    dayIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DailyQuiz extends BaseContract {
  connect(runner?: ContractRunner | null): DailyQuiz;
  waitForDeployment(): Promise<this>;

  interface: DailyQuizInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  QUESTIONS_PER_DAY: TypedContractMethod<[], [bigint], "view">;

  achievementManager: TypedContractMethod<[], [string], "view">;

  canPlay: TypedContractMethod<[player: AddressLike], [boolean], "view">;

  dailyMerkleRoot: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  dailyScore: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  enterQuiz: TypedContractMethod<[], [void], "nonpayable">;

  getTodayScore: TypedContractMethod<
    [player: AddressLike],
    [[bigint, boolean]],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  isTodayReady: TypedContractMethod<[], [boolean], "view">;

  lastPlayedDay: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  playerProfile: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDailyMerkleRoot: TypedContractMethod<
    [root: BytesLike, dayIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitAnswers: TypedContractMethod<
    [answerHashes: BytesLike[], proofs: BytesLike[][]],
    [void],
    "nonpayable"
  >;

  todayIndex: TypedContractMethod<[], [bigint], "view">;

  totalGamesPlayed: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "QUESTIONS_PER_DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "achievementManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canPlay"
  ): TypedContractMethod<[player: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dailyMerkleRoot"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "dailyScore"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "enterQuiz"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTodayScore"
  ): TypedContractMethod<[player: AddressLike], [[bigint, boolean]], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTodayReady"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastPlayedDay"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playerProfile"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyMerkleRoot"
  ): TypedContractMethod<
    [root: BytesLike, dayIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitAnswers"
  ): TypedContractMethod<
    [answerHashes: BytesLike[], proofs: BytesLike[][]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "todayIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalGamesPlayed"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MerkleRootSet"
  ): TypedContractEvent<
    MerkleRootSetEvent.InputTuple,
    MerkleRootSetEvent.OutputTuple,
    MerkleRootSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "QuizCompleted"
  ): TypedContractEvent<
    QuizCompletedEvent.InputTuple,
    QuizCompletedEvent.OutputTuple,
    QuizCompletedEvent.OutputObject
  >;
  getEvent(
    key: "QuizEntered"
  ): TypedContractEvent<
    QuizEnteredEvent.InputTuple,
    QuizEnteredEvent.OutputTuple,
    QuizEnteredEvent.OutputObject
  >;

  filters: {
    "MerkleRootSet(uint256,bytes32)": TypedContractEvent<
      MerkleRootSetEvent.InputTuple,
      MerkleRootSetEvent.OutputTuple,
      MerkleRootSetEvent.OutputObject
    >;
    MerkleRootSet: TypedContractEvent<
      MerkleRootSetEvent.InputTuple,
      MerkleRootSetEvent.OutputTuple,
      MerkleRootSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "QuizCompleted(address,uint256,uint8,uint256)": TypedContractEvent<
      QuizCompletedEvent.InputTuple,
      QuizCompletedEvent.OutputTuple,
      QuizCompletedEvent.OutputObject
    >;
    QuizCompleted: TypedContractEvent<
      QuizCompletedEvent.InputTuple,
      QuizCompletedEvent.OutputTuple,
      QuizCompletedEvent.OutputObject
    >;

    "QuizEntered(address,uint256)": TypedContractEvent<
      QuizEnteredEvent.InputTuple,
      QuizEnteredEvent.OutputTuple,
      QuizEnteredEvent.OutputObject
    >;
    QuizEntered: TypedContractEvent<
      QuizEnteredEvent.InputTuple,
      QuizEnteredEvent.OutputTuple,
      QuizEnteredEvent.OutputObject
    >;
  };
}
