/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AchievementManager } from "./AchievementManager";
export type { BadgeNFT } from "./BadgeNFT";
export type { DailyQuiz } from "./DailyQuiz";
export type { PlayerProfile } from "./PlayerProfile";
export type { RewardPool } from "./RewardPool";
