/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PlayerProfileInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAY"
      | "GRACE_PERIOD"
      | "achievementManager"
      | "getProfile"
      | "hasAchievement"
      | "monthlyEpoch"
      | "monthlyScoreByEpoch"
      | "owner"
      | "quizContract"
      | "recordPlay"
      | "renounceOwnership"
      | "resetPeriodScores"
      | "seasonEpoch"
      | "seasonScoreByEpoch"
      | "setAchievementFlag"
      | "setAchievementManager"
      | "setQuizContract"
      | "streakBoosts"
      | "streakThresholds"
      | "transferOwnership"
      | "weeklyEpoch"
      | "weeklyScoreByEpoch"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PeriodReset"
      | "ProfileCreated"
      | "ScoreUpdated"
      | "StreakUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "DAY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "achievementManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAchievement",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyScoreByEpoch",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quizContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordPlay",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetPeriodScores",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "seasonEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonScoreByEpoch",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAchievementFlag",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAchievementManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuizContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "streakBoosts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streakThresholds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "weeklyScoreByEpoch",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "DAY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "achievementManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getProfile", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyScoreByEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quizContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordPlay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetPeriodScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonScoreByEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAchievementFlag",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAchievementManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setQuizContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streakBoosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "streakThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weeklyEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "weeklyScoreByEpoch",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PeriodResetEvent {
  export type InputTuple = [period: BigNumberish];
  export type OutputTuple = [period: bigint];
  export interface OutputObject {
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfileCreatedEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    player: AddressLike,
    rawScore: BigNumberish,
    boostedScore: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    rawScore: bigint,
    boostedScore: bigint
  ];
  export interface OutputObject {
    player: string;
    rawScore: bigint;
    boostedScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StreakUpdatedEvent {
  export type InputTuple = [
    player: AddressLike,
    streakDays: BigNumberish,
    boostMultiplier: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    streakDays: bigint,
    boostMultiplier: bigint
  ];
  export interface OutputObject {
    player: string;
    streakDays: bigint;
    boostMultiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlayerProfile extends BaseContract {
  connect(runner?: ContractRunner | null): PlayerProfile;
  waitForDeployment(): Promise<this>;

  interface: PlayerProfileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAY: TypedContractMethod<[], [bigint], "view">;

  GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  achievementManager: TypedContractMethod<[], [string], "view">;

  getProfile: TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        weeklyScore: bigint;
        monthlyScore: bigint;
        seasonScore: bigint;
        streakDays: bigint;
        boostMultiplier: bigint;
        achievementFlags: bigint;
      }
    ],
    "view"
  >;

  hasAchievement: TypedContractMethod<
    [player: AddressLike, flagIndex: BigNumberish],
    [boolean],
    "view"
  >;

  monthlyEpoch: TypedContractMethod<[], [bigint], "view">;

  monthlyScoreByEpoch: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  quizContract: TypedContractMethod<[], [string], "view">;

  recordPlay: TypedContractMethod<
    [player: AddressLike, rawScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetPeriodScores: TypedContractMethod<
    [period: BigNumberish],
    [void],
    "nonpayable"
  >;

  seasonEpoch: TypedContractMethod<[], [bigint], "view">;

  seasonScoreByEpoch: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  setAchievementFlag: TypedContractMethod<
    [player: AddressLike, flagIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAchievementManager: TypedContractMethod<
    [_manager: AddressLike],
    [void],
    "nonpayable"
  >;

  setQuizContract: TypedContractMethod<
    [_quiz: AddressLike],
    [void],
    "nonpayable"
  >;

  streakBoosts: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  streakThresholds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  weeklyEpoch: TypedContractMethod<[], [bigint], "view">;

  weeklyScoreByEpoch: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "achievementManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getProfile"
  ): TypedContractMethod<
    [player: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalScore: bigint;
        weeklyScore: bigint;
        monthlyScore: bigint;
        seasonScore: bigint;
        streakDays: bigint;
        boostMultiplier: bigint;
        achievementFlags: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAchievement"
  ): TypedContractMethod<
    [player: AddressLike, flagIndex: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "monthlyEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "monthlyScoreByEpoch"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quizContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordPlay"
  ): TypedContractMethod<
    [player: AddressLike, rawScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetPeriodScores"
  ): TypedContractMethod<[period: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasonEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seasonScoreByEpoch"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setAchievementFlag"
  ): TypedContractMethod<
    [player: AddressLike, flagIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAchievementManager"
  ): TypedContractMethod<[_manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuizContract"
  ): TypedContractMethod<[_quiz: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "streakBoosts"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "streakThresholds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "weeklyEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "weeklyScoreByEpoch"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PeriodReset"
  ): TypedContractEvent<
    PeriodResetEvent.InputTuple,
    PeriodResetEvent.OutputTuple,
    PeriodResetEvent.OutputObject
  >;
  getEvent(
    key: "ProfileCreated"
  ): TypedContractEvent<
    ProfileCreatedEvent.InputTuple,
    ProfileCreatedEvent.OutputTuple,
    ProfileCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StreakUpdated"
  ): TypedContractEvent<
    StreakUpdatedEvent.InputTuple,
    StreakUpdatedEvent.OutputTuple,
    StreakUpdatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PeriodReset(uint8)": TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;
    PeriodReset: TypedContractEvent<
      PeriodResetEvent.InputTuple,
      PeriodResetEvent.OutputTuple,
      PeriodResetEvent.OutputObject
    >;

    "ProfileCreated(address)": TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;
    ProfileCreated: TypedContractEvent<
      ProfileCreatedEvent.InputTuple,
      ProfileCreatedEvent.OutputTuple,
      ProfileCreatedEvent.OutputObject
    >;

    "ScoreUpdated(address,uint256,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;

    "StreakUpdated(address,uint256,uint256)": TypedContractEvent<
      StreakUpdatedEvent.InputTuple,
      StreakUpdatedEvent.OutputTuple,
      StreakUpdatedEvent.OutputObject
    >;
    StreakUpdated: TypedContractEvent<
      StreakUpdatedEvent.InputTuple,
      StreakUpdatedEvent.OutputTuple,
      StreakUpdatedEvent.OutputObject
    >;
  };
}
