/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RewardPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ACHIEVE_SHARE"
      | "MONTHLY_SPLIT"
      | "PLATFORM_SHARE"
      | "REWARD_SHARE"
      | "SEASON_SPLIT"
      | "WEEKLY_SPLIT"
      | "achievementPool"
      | "badgeNFT"
      | "claimAll"
      | "claimNFT"
      | "claimUSDC"
      | "claimableNFT"
      | "claimableUSDC"
      | "distributeRewards"
      | "getPoolBalances"
      | "monthlyPool"
      | "owner"
      | "platform"
      | "quizContract"
      | "receiveFee"
      | "renounceOwnership"
      | "seasonPool"
      | "setQuizContract"
      | "transferOwnership"
      | "usdc"
      | "weeklyPool"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Claimed"
      | "FeeReceived"
      | "NFTClaimed"
      | "NFTRewardSet"
      | "OwnershipTransferred"
      | "RewardsDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ACHIEVE_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MONTHLY_SPLIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PLATFORM_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REWARD_SHARE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SEASON_SPLIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WEEKLY_SPLIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "achievementPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "badgeNFT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimAll",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claimUSDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimableNFT",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableUSDC",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeRewards",
    values: [BigNumberish, AddressLike[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolBalances",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "monthlyPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "platform", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "quizContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setQuizContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "weeklyPool",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "ACHIEVE_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MONTHLY_SPLIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PLATFORM_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REWARD_SHARE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SEASON_SPLIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "WEEKLY_SPLIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "achievementPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "badgeNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimAll", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimUSDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimableNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableUSDC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "monthlyPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "platform", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quizContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receiveFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seasonPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setQuizContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weeklyPool", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [player: AddressLike, usdcAmount: BigNumberish];
  export type OutputTuple = [player: string, usdcAmount: bigint];
  export interface OutputObject {
    player: string;
    usdcAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeReceivedEvent {
  export type InputTuple = [
    amount: BigNumberish,
    toReward: BigNumberish,
    toPlatform: BigNumberish,
    toAchieve: BigNumberish
  ];
  export type OutputTuple = [
    amount: bigint,
    toReward: bigint,
    toPlatform: bigint,
    toAchieve: bigint
  ];
  export interface OutputObject {
    amount: bigint;
    toReward: bigint;
    toPlatform: bigint;
    toAchieve: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTClaimedEvent {
  export type InputTuple = [player: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [player: string, tokenId: bigint];
  export interface OutputObject {
    player: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NFTRewardSetEvent {
  export type InputTuple = [player: AddressLike, tokenId: BigNumberish];
  export type OutputTuple = [player: string, tokenId: bigint];
  export interface OutputObject {
    player: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    period: BigNumberish,
    winners: AddressLike[],
    amounts: BigNumberish[]
  ];
  export type OutputTuple = [
    period: bigint,
    winners: string[],
    amounts: bigint[]
  ];
  export interface OutputObject {
    period: bigint;
    winners: string[];
    amounts: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RewardPool extends BaseContract {
  connect(runner?: ContractRunner | null): RewardPool;
  waitForDeployment(): Promise<this>;

  interface: RewardPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ACHIEVE_SHARE: TypedContractMethod<[], [bigint], "view">;

  MONTHLY_SPLIT: TypedContractMethod<[], [bigint], "view">;

  PLATFORM_SHARE: TypedContractMethod<[], [bigint], "view">;

  REWARD_SHARE: TypedContractMethod<[], [bigint], "view">;

  SEASON_SPLIT: TypedContractMethod<[], [bigint], "view">;

  WEEKLY_SPLIT: TypedContractMethod<[], [bigint], "view">;

  achievementPool: TypedContractMethod<[], [bigint], "view">;

  badgeNFT: TypedContractMethod<[], [string], "view">;

  claimAll: TypedContractMethod<
    [nftTokenIds: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  claimNFT: TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;

  claimUSDC: TypedContractMethod<[], [void], "nonpayable">;

  claimableNFT: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  claimableUSDC: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  distributeRewards: TypedContractMethod<
    [
      period: BigNumberish,
      winners: AddressLike[],
      amounts: BigNumberish[],
      nftTokenIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getPoolBalances: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        weekly: bigint;
        monthly: bigint;
        season: bigint;
        achievement: bigint;
      }
    ],
    "view"
  >;

  monthlyPool: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  platform: TypedContractMethod<[], [string], "view">;

  quizContract: TypedContractMethod<[], [string], "view">;

  receiveFee: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  seasonPool: TypedContractMethod<[], [bigint], "view">;

  setQuizContract: TypedContractMethod<
    [_quiz: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  weeklyPool: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ACHIEVE_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MONTHLY_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PLATFORM_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REWARD_SHARE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SEASON_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WEEKLY_SPLIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "achievementPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "badgeNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimAll"
  ): TypedContractMethod<[nftTokenIds: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNFT"
  ): TypedContractMethod<[tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimUSDC"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableNFT"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimableUSDC"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributeRewards"
  ): TypedContractMethod<
    [
      period: BigNumberish,
      winners: AddressLike[],
      amounts: BigNumberish[],
      nftTokenIds: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getPoolBalances"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        weekly: bigint;
        monthly: bigint;
        season: bigint;
        achievement: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "monthlyPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platform"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quizContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveFee"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasonPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setQuizContract"
  ): TypedContractMethod<[_quiz: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "weeklyPool"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "FeeReceived"
  ): TypedContractEvent<
    FeeReceivedEvent.InputTuple,
    FeeReceivedEvent.OutputTuple,
    FeeReceivedEvent.OutputObject
  >;
  getEvent(
    key: "NFTClaimed"
  ): TypedContractEvent<
    NFTClaimedEvent.InputTuple,
    NFTClaimedEvent.OutputTuple,
    NFTClaimedEvent.OutputObject
  >;
  getEvent(
    key: "NFTRewardSet"
  ): TypedContractEvent<
    NFTRewardSetEvent.InputTuple,
    NFTRewardSetEvent.OutputTuple,
    NFTRewardSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;

  filters: {
    "Claimed(address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "FeeReceived(uint256,uint256,uint256,uint256)": TypedContractEvent<
      FeeReceivedEvent.InputTuple,
      FeeReceivedEvent.OutputTuple,
      FeeReceivedEvent.OutputObject
    >;
    FeeReceived: TypedContractEvent<
      FeeReceivedEvent.InputTuple,
      FeeReceivedEvent.OutputTuple,
      FeeReceivedEvent.OutputObject
    >;

    "NFTClaimed(address,uint256)": TypedContractEvent<
      NFTClaimedEvent.InputTuple,
      NFTClaimedEvent.OutputTuple,
      NFTClaimedEvent.OutputObject
    >;
    NFTClaimed: TypedContractEvent<
      NFTClaimedEvent.InputTuple,
      NFTClaimedEvent.OutputTuple,
      NFTClaimedEvent.OutputObject
    >;

    "NFTRewardSet(address,uint256)": TypedContractEvent<
      NFTRewardSetEvent.InputTuple,
      NFTRewardSetEvent.OutputTuple,
      NFTRewardSetEvent.OutputObject
    >;
    NFTRewardSet: TypedContractEvent<
      NFTRewardSetEvent.InputTuple,
      NFTRewardSetEvent.OutputTuple,
      NFTRewardSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsDistributed(uint8,address[],uint256[])": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
  };
}
